### PR TITLE
updated

### PR DESCRIPTION
**Pull request by PraveenBalaraj98**
hi lead
i have updated the code please review and update
regards 
praveen.B

### CODE REVIEW

**Comment by swati9873** [comment]
hi tester
Go through your report. You can do changes..

**Review by swati9873 — CHANGES_REQUESTED** [review]
Hi Tester
plz give some other name Runner class is not ok.

**Comment by PraveenBalaraj98** [comment]
> Hi Tester plz give some other name Runner class is not ok.

OK lead : \

**Review by swati9873 — APPROVED** [review]

**Review by swati9873 — APPROVED** [review]

**Review by Singathiramanan — APPROVED** [review]

**Review by swati9873 — APPROVED** [review]

**Comment by swati9873** [comment]
hi tester
you can do

**Comment by swati9873** [comment]
dsdfghj

**Review by swati9873 — APPROVED** [review]
ertyui

**Pull request merged**
